// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v5.29.3
// source: shared/proto/gateway/gateway.proto

package gateway

import (
	common "github.com/frankieli/game_product/shared/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BroadcastReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameCode string     `protobuf:"bytes,1,opt,name=game_code,json=gameCode,proto3" json:"game_code,omitempty"`
	Event    *anypb.Any `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"` // Dynamic payload (e.g., ColorGameRoundStateBRC)
}

func (x *BroadcastReq) Reset() {
	*x = BroadcastReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_gateway_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastReq) ProtoMessage() {}

func (x *BroadcastReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastReq.ProtoReflect.Descriptor instead.
func (*BroadcastReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_gateway_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *BroadcastReq) GetGameCode() string {
	if x != nil {
		return x.GameCode
	}
	return ""
}

func (x *BroadcastReq) GetEvent() *anypb.Any {
	if x != nil {
		return x.Event
	}
	return nil
}

type BroadcastRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode common.ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=common.ErrorCode" json:"error_code,omitempty"`
	Success   bool             `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error     string           `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *BroadcastRsp) Reset() {
	*x = BroadcastRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_gateway_gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRsp) ProtoMessage() {}

func (x *BroadcastRsp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRsp.ProtoReflect.Descriptor instead.
func (*BroadcastRsp) Descriptor() ([]byte, []int) {
	return file_shared_proto_gateway_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *BroadcastRsp) GetErrorCode() common.ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return common.ErrorCode(0)
}

func (x *BroadcastRsp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BroadcastRsp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SendToUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int64      `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GameCode string     `protobuf:"bytes,2,opt,name=game_code,json=gameCode,proto3" json:"game_code,omitempty"`
	Event    *anypb.Any `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *SendToUserReq) Reset() {
	*x = SendToUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_gateway_gateway_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendToUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToUserReq) ProtoMessage() {}

func (x *SendToUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToUserReq.ProtoReflect.Descriptor instead.
func (*SendToUserReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_gateway_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *SendToUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendToUserReq) GetGameCode() string {
	if x != nil {
		return x.GameCode
	}
	return ""
}

func (x *SendToUserReq) GetEvent() *anypb.Any {
	if x != nil {
		return x.Event
	}
	return nil
}

type SendToUserRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode common.ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=common.ErrorCode" json:"error_code,omitempty"`
	Success   bool             `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error     string           `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SendToUserRsp) Reset() {
	*x = SendToUserRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_gateway_gateway_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendToUserRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToUserRsp) ProtoMessage() {}

func (x *SendToUserRsp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_gateway_gateway_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToUserRsp.ProtoReflect.Descriptor instead.
func (*SendToUserRsp) Descriptor() ([]byte, []int) {
	return file_shared_proto_gateway_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *SendToUserRsp) GetErrorCode() common.ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return common.ErrorCode(0)
}

func (x *SendToUserRsp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendToUserRsp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_shared_proto_gateway_gateway_proto protoreflect.FileDescriptor

var file_shared_proto_gateway_gateway_proto_rawDesc = []byte{
	0x0a, 0x22, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x1a, 0x20, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a, 0x0c, 0x42, 0x72,
	0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61,
	0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67,
	0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x22, 0x70, 0x0a, 0x0c, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74,
	0x52, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x71, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2a, 0x0a, 0x05,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e,
	0x79, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x71, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64,
	0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x0a, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x89, 0x01, 0x0a, 0x0e,
	0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39,
	0x0a, 0x09, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x15, 0x2e, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x15, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x42, 0x72, 0x6f,
	0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x0a, 0x53, 0x65, 0x6e,
	0x64, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a,
	0x16, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x73, 0x70, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x65, 0x6c, 0x69, 0x2f,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2f, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shared_proto_gateway_gateway_proto_rawDescOnce sync.Once
	file_shared_proto_gateway_gateway_proto_rawDescData = file_shared_proto_gateway_gateway_proto_rawDesc
)

func file_shared_proto_gateway_gateway_proto_rawDescGZIP() []byte {
	file_shared_proto_gateway_gateway_proto_rawDescOnce.Do(func() {
		file_shared_proto_gateway_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_shared_proto_gateway_gateway_proto_rawDescData)
	})
	return file_shared_proto_gateway_gateway_proto_rawDescData
}

var file_shared_proto_gateway_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shared_proto_gateway_gateway_proto_goTypes = []interface{}{
	(*BroadcastReq)(nil),  // 0: gateway.BroadcastReq
	(*BroadcastRsp)(nil),  // 1: gateway.BroadcastRsp
	(*SendToUserReq)(nil), // 2: gateway.SendToUserReq
	(*SendToUserRsp)(nil), // 3: gateway.SendToUserRsp
	(*anypb.Any)(nil),     // 4: google.protobuf.Any
	(common.ErrorCode)(0), // 5: common.ErrorCode
}
var file_shared_proto_gateway_gateway_proto_depIdxs = []int32{
	4, // 0: gateway.BroadcastReq.event:type_name -> google.protobuf.Any
	5, // 1: gateway.BroadcastRsp.error_code:type_name -> common.ErrorCode
	4, // 2: gateway.SendToUserReq.event:type_name -> google.protobuf.Any
	5, // 3: gateway.SendToUserRsp.error_code:type_name -> common.ErrorCode
	0, // 4: gateway.GatewayService.Broadcast:input_type -> gateway.BroadcastReq
	2, // 5: gateway.GatewayService.SendToUser:input_type -> gateway.SendToUserReq
	1, // 6: gateway.GatewayService.Broadcast:output_type -> gateway.BroadcastRsp
	3, // 7: gateway.GatewayService.SendToUser:output_type -> gateway.SendToUserRsp
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_shared_proto_gateway_gateway_proto_init() }
func file_shared_proto_gateway_gateway_proto_init() {
	if File_shared_proto_gateway_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shared_proto_gateway_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_gateway_gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_gateway_gateway_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendToUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_gateway_gateway_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendToUserRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shared_proto_gateway_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_gateway_gateway_proto_goTypes,
		DependencyIndexes: file_shared_proto_gateway_gateway_proto_depIdxs,
		MessageInfos:      file_shared_proto_gateway_gateway_proto_msgTypes,
	}.Build()
	File_shared_proto_gateway_gateway_proto = out.File
	file_shared_proto_gateway_gateway_proto_rawDesc = nil
	file_shared_proto_gateway_gateway_proto_goTypes = nil
	file_shared_proto_gateway_gateway_proto_depIdxs = nil
}
