// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v5.29.3
// source: shared/proto/admin/admin.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollectRespChunk_DataType int32

const (
	CollectRespChunk_UNKNOWN        CollectRespChunk_DataType = 0
	CollectRespChunk_CPU_PROFILE    CollectRespChunk_DataType = 1
	CollectRespChunk_TRACE_DATA     CollectRespChunk_DataType = 2
	CollectRespChunk_HEAP_SNAPSHOT  CollectRespChunk_DataType = 3
	CollectRespChunk_GOROUTINE_DUMP CollectRespChunk_DataType = 4
	CollectRespChunk_BLOCK_PROFILE  CollectRespChunk_DataType = 5
	CollectRespChunk_MUTEX_PROFILE  CollectRespChunk_DataType = 6
)

// Enum value maps for CollectRespChunk_DataType.
var (
	CollectRespChunk_DataType_name = map[int32]string{
		0: "UNKNOWN",
		1: "CPU_PROFILE",
		2: "TRACE_DATA",
		3: "HEAP_SNAPSHOT",
		4: "GOROUTINE_DUMP",
		5: "BLOCK_PROFILE",
		6: "MUTEX_PROFILE",
	}
	CollectRespChunk_DataType_value = map[string]int32{
		"UNKNOWN":        0,
		"CPU_PROFILE":    1,
		"TRACE_DATA":     2,
		"HEAP_SNAPSHOT":  3,
		"GOROUTINE_DUMP": 4,
		"BLOCK_PROFILE":  5,
		"MUTEX_PROFILE":  6,
	}
)

func (x CollectRespChunk_DataType) Enum() *CollectRespChunk_DataType {
	p := new(CollectRespChunk_DataType)
	*p = x
	return p
}

func (x CollectRespChunk_DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CollectRespChunk_DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_admin_admin_proto_enumTypes[0].Descriptor()
}

func (CollectRespChunk_DataType) Type() protoreflect.EnumType {
	return &file_shared_proto_admin_admin_proto_enumTypes[0]
}

func (x CollectRespChunk_DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CollectRespChunk_DataType.Descriptor instead.
func (CollectRespChunk_DataType) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_admin_admin_proto_rawDescGZIP(), []int{1, 0}
}

type CollectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Duration to profile (e.g., 30 seconds).
	DurationSeconds int32 `protobuf:"varint,1,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
}

func (x *CollectReq) Reset() {
	*x = CollectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_admin_admin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectReq) ProtoMessage() {}

func (x *CollectReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_admin_admin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectReq.ProtoReflect.Descriptor instead.
func (*CollectReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_admin_admin_proto_rawDescGZIP(), []int{0}
}

func (x *CollectReq) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type CollectRespChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataType    CollectRespChunk_DataType `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3,enum=admin.CollectRespChunk_DataType" json:"data_type,omitempty"` // Type of data in this chunk
	Data        []byte                    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                                               // Binary chunk data
	Timestamp   int64                     `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                    // Unix timestamp (sent in at least one chunk)
	ServiceName string                    `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`                              // Name of the service (sent in at least one chunk)
}

func (x *CollectRespChunk) Reset() {
	*x = CollectRespChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_admin_admin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectRespChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectRespChunk) ProtoMessage() {}

func (x *CollectRespChunk) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_admin_admin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectRespChunk.ProtoReflect.Descriptor instead.
func (*CollectRespChunk) Descriptor() ([]byte, []int) {
	return file_shared_proto_admin_admin_proto_rawDescGZIP(), []int{1}
}

func (x *CollectRespChunk) GetDataType() CollectRespChunk_DataType {
	if x != nil {
		return x.DataType
	}
	return CollectRespChunk_UNKNOWN
}

func (x *CollectRespChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CollectRespChunk) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CollectRespChunk) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

// CollectResp is the aggregated result reconstructed from chunks (Client-side use)
type CollectResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpuProfile    []byte `protobuf:"bytes,1,opt,name=cpu_profile,json=cpuProfile,proto3" json:"cpu_profile,omitempty"`          // Binary data for pprof CPU profile
	TraceData     []byte `protobuf:"bytes,2,opt,name=trace_data,json=traceData,proto3" json:"trace_data,omitempty"`             // Binary data for runtime execution trace
	HeapSnapshot  []byte `protobuf:"bytes,3,opt,name=heap_snapshot,json=heapSnapshot,proto3" json:"heap_snapshot,omitempty"`    // Binary data for pprof Heap profile
	GoroutineDump []byte `protobuf:"bytes,4,opt,name=goroutine_dump,json=goroutineDump,proto3" json:"goroutine_dump,omitempty"` // Binary/Text data for Goroutine stack traces
	Timestamp     int64  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                             // Unix timestamp of when collection finished
	ServiceName   string `protobuf:"bytes,6,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`       // Name of the service (e.g., "user-service")
	BlockProfile  []byte `protobuf:"bytes,7,opt,name=block_profile,json=blockProfile,proto3" json:"block_profile,omitempty"`    // Binary data for runtime Block profile
	MutexProfile  []byte `protobuf:"bytes,8,opt,name=mutex_profile,json=mutexProfile,proto3" json:"mutex_profile,omitempty"`    // Binary data for runtime Mutex profile
}

func (x *CollectResp) Reset() {
	*x = CollectResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_admin_admin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectResp) ProtoMessage() {}

func (x *CollectResp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_admin_admin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectResp.ProtoReflect.Descriptor instead.
func (*CollectResp) Descriptor() ([]byte, []int) {
	return file_shared_proto_admin_admin_proto_rawDescGZIP(), []int{2}
}

func (x *CollectResp) GetCpuProfile() []byte {
	if x != nil {
		return x.CpuProfile
	}
	return nil
}

func (x *CollectResp) GetTraceData() []byte {
	if x != nil {
		return x.TraceData
	}
	return nil
}

func (x *CollectResp) GetHeapSnapshot() []byte {
	if x != nil {
		return x.HeapSnapshot
	}
	return nil
}

func (x *CollectResp) GetGoroutineDump() []byte {
	if x != nil {
		return x.GoroutineDump
	}
	return nil
}

func (x *CollectResp) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CollectResp) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CollectResp) GetBlockProfile() []byte {
	if x != nil {
		return x.BlockProfile
	}
	return nil
}

func (x *CollectResp) GetMutexProfile() []byte {
	if x != nil {
		return x.MutexProfile
	}
	return nil
}

var File_shared_proto_admin_admin_proto protoreflect.FileDescriptor

var file_shared_proto_admin_admin_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x22, 0x37, 0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x10, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x22, 0xae, 0x02, 0x0a, 0x10, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x3d, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x08, 0x44, 0x61,
	0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x50, 0x55, 0x5f, 0x50, 0x52, 0x4f, 0x46, 0x49,
	0x4c, 0x45, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x52, 0x41, 0x43, 0x45, 0x5f, 0x44, 0x41,
	0x54, 0x41, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x48, 0x45, 0x41, 0x50, 0x5f, 0x53, 0x4e, 0x41,
	0x50, 0x53, 0x48, 0x4f, 0x54, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x47, 0x4f, 0x52, 0x4f, 0x55,
	0x54, 0x49, 0x4e, 0x45, 0x5f, 0x44, 0x55, 0x4d, 0x50, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x42,
	0x4c, 0x4f, 0x43, 0x4b, 0x5f, 0x50, 0x52, 0x4f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x05, 0x12, 0x11,
	0x0a, 0x0d, 0x4d, 0x55, 0x54, 0x45, 0x58, 0x5f, 0x50, 0x52, 0x4f, 0x46, 0x49, 0x4c, 0x45, 0x10,
	0x06, 0x22, 0xa4, 0x02, 0x0a, 0x0b, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x70, 0x75, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x70, 0x75, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x74, 0x72, 0x61, 0x63, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x23, 0x0a, 0x0d, 0x68, 0x65, 0x61, 0x70, 0x5f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x68, 0x65, 0x61, 0x70, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x67, 0x6f, 0x72, 0x6f, 0x75, 0x74,
	0x69, 0x6e, 0x65, 0x5f, 0x64, 0x75, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d,
	0x67, 0x6f, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x44, 0x75, 0x6d, 0x70, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x75, 0x74, 0x65, 0x78, 0x5f, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x6d, 0x75, 0x74, 0x65,
	0x78, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x32, 0x56, 0x0a, 0x0c, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x16, 0x43, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x11, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x30, 0x01,
	0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66,
	0x72, 0x61, 0x6e, 0x6b, 0x69, 0x65, 0x6c, 0x69, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shared_proto_admin_admin_proto_rawDescOnce sync.Once
	file_shared_proto_admin_admin_proto_rawDescData = file_shared_proto_admin_admin_proto_rawDesc
)

func file_shared_proto_admin_admin_proto_rawDescGZIP() []byte {
	file_shared_proto_admin_admin_proto_rawDescOnce.Do(func() {
		file_shared_proto_admin_admin_proto_rawDescData = protoimpl.X.CompressGZIP(file_shared_proto_admin_admin_proto_rawDescData)
	})
	return file_shared_proto_admin_admin_proto_rawDescData
}

var file_shared_proto_admin_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_proto_admin_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shared_proto_admin_admin_proto_goTypes = []interface{}{
	(CollectRespChunk_DataType)(0), // 0: admin.CollectRespChunk.DataType
	(*CollectReq)(nil),             // 1: admin.CollectReq
	(*CollectRespChunk)(nil),       // 2: admin.CollectRespChunk
	(*CollectResp)(nil),            // 3: admin.CollectResp
}
var file_shared_proto_admin_admin_proto_depIdxs = []int32{
	0, // 0: admin.CollectRespChunk.data_type:type_name -> admin.CollectRespChunk.DataType
	1, // 1: admin.AdminService.CollectPerformanceData:input_type -> admin.CollectReq
	2, // 2: admin.AdminService.CollectPerformanceData:output_type -> admin.CollectRespChunk
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shared_proto_admin_admin_proto_init() }
func file_shared_proto_admin_admin_proto_init() {
	if File_shared_proto_admin_admin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shared_proto_admin_admin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_admin_admin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectRespChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_admin_admin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shared_proto_admin_admin_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_admin_admin_proto_goTypes,
		DependencyIndexes: file_shared_proto_admin_admin_proto_depIdxs,
		EnumInfos:         file_shared_proto_admin_admin_proto_enumTypes,
		MessageInfos:      file_shared_proto_admin_admin_proto_msgTypes,
	}.Build()
	File_shared_proto_admin_admin_proto = out.File
	file_shared_proto_admin_admin_proto_rawDesc = nil
	file_shared_proto_admin_admin_proto_goTypes = nil
	file_shared_proto_admin_admin_proto_depIdxs = nil
}
