// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: shared/proto/admin/admin.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	// CollectPerformanceData captures CPU profile, Heap snapshot, Goroutine dump, and Trace
	// for a specified duration and returns them as binary data.
	CollectPerformanceData(ctx context.Context, in *CollectReq, opts ...grpc.CallOption) (AdminService_CollectPerformanceDataClient, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) CollectPerformanceData(ctx context.Context, in *CollectReq, opts ...grpc.CallOption) (AdminService_CollectPerformanceDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &AdminService_ServiceDesc.Streams[0], "/admin.AdminService/CollectPerformanceData", opts...)
	if err != nil {
		return nil, err
	}
	x := &adminServiceCollectPerformanceDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AdminService_CollectPerformanceDataClient interface {
	Recv() (*CollectRespChunk, error)
	grpc.ClientStream
}

type adminServiceCollectPerformanceDataClient struct {
	grpc.ClientStream
}

func (x *adminServiceCollectPerformanceDataClient) Recv() (*CollectRespChunk, error) {
	m := new(CollectRespChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility
type AdminServiceServer interface {
	// CollectPerformanceData captures CPU profile, Heap snapshot, Goroutine dump, and Trace
	// for a specified duration and returns them as binary data.
	CollectPerformanceData(*CollectReq, AdminService_CollectPerformanceDataServer) error
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAdminServiceServer struct {
}

func (UnimplementedAdminServiceServer) CollectPerformanceData(*CollectReq, AdminService_CollectPerformanceDataServer) error {
	return status.Errorf(codes.Unimplemented, "method CollectPerformanceData not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_CollectPerformanceData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CollectReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdminServiceServer).CollectPerformanceData(m, &adminServiceCollectPerformanceDataServer{stream})
}

type AdminService_CollectPerformanceDataServer interface {
	Send(*CollectRespChunk) error
	grpc.ServerStream
}

type adminServiceCollectPerformanceDataServer struct {
	grpc.ServerStream
}

func (x *adminServiceCollectPerformanceDataServer) Send(m *CollectRespChunk) error {
	return x.ServerStream.SendMsg(m)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CollectPerformanceData",
			Handler:       _AdminService_CollectPerformanceData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "shared/proto/admin/admin.proto",
}
