// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v5.29.3
// source: shared/proto/admin/admin.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Duration to profile (e.g., 30 seconds).
	DurationSeconds int32 `protobuf:"varint,1,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
}

func (x *CollectReq) Reset() {
	*x = CollectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_admin_admin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectReq) ProtoMessage() {}

func (x *CollectReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_admin_admin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectReq.ProtoReflect.Descriptor instead.
func (*CollectReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_admin_admin_proto_rawDescGZIP(), []int{0}
}

func (x *CollectReq) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type CollectResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpuProfile    []byte `protobuf:"bytes,1,opt,name=cpu_profile,json=cpuProfile,proto3" json:"cpu_profile,omitempty"`          // Binary data for pprof CPU profile
	TraceData     []byte `protobuf:"bytes,2,opt,name=trace_data,json=traceData,proto3" json:"trace_data,omitempty"`             // Binary data for runtime execution trace
	HeapSnapshot  []byte `protobuf:"bytes,3,opt,name=heap_snapshot,json=heapSnapshot,proto3" json:"heap_snapshot,omitempty"`    // Binary data for pprof Heap profile
	GoroutineDump []byte `protobuf:"bytes,4,opt,name=goroutine_dump,json=goroutineDump,proto3" json:"goroutine_dump,omitempty"` // Binary/Text data for Goroutine stack traces
	Timestamp     int64  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                             // Unix timestamp of when collection finished
	ServiceName   string `protobuf:"bytes,6,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`       // Name of the service (e.g., "user-service")
}

func (x *CollectResp) Reset() {
	*x = CollectResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_admin_admin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectResp) ProtoMessage() {}

func (x *CollectResp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_admin_admin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectResp.ProtoReflect.Descriptor instead.
func (*CollectResp) Descriptor() ([]byte, []int) {
	return file_shared_proto_admin_admin_proto_rawDescGZIP(), []int{1}
}

func (x *CollectResp) GetCpuProfile() []byte {
	if x != nil {
		return x.CpuProfile
	}
	return nil
}

func (x *CollectResp) GetTraceData() []byte {
	if x != nil {
		return x.TraceData
	}
	return nil
}

func (x *CollectResp) GetHeapSnapshot() []byte {
	if x != nil {
		return x.HeapSnapshot
	}
	return nil
}

func (x *CollectResp) GetGoroutineDump() []byte {
	if x != nil {
		return x.GoroutineDump
	}
	return nil
}

func (x *CollectResp) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CollectResp) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

var File_shared_proto_admin_admin_proto protoreflect.FileDescriptor

var file_shared_proto_admin_admin_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x22, 0x37, 0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x10, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x22, 0xda, 0x01, 0x0a, 0x0b, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x70, 0x75, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x70, 0x75, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x74, 0x72, 0x61, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x23, 0x0a, 0x0d, 0x68, 0x65, 0x61, 0x70, 0x5f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x68, 0x65, 0x61, 0x70, 0x53, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x67, 0x6f, 0x72, 0x6f, 0x75, 0x74, 0x69,
	0x6e, 0x65, 0x5f, 0x64, 0x75, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x67,
	0x6f, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x44, 0x75, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x4f, 0x0a,
	0x0c, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a,
	0x16, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x6e, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x11, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x36,
	0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x72, 0x61,
	0x6e, 0x6b, 0x69, 0x65, 0x6c, 0x69, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shared_proto_admin_admin_proto_rawDescOnce sync.Once
	file_shared_proto_admin_admin_proto_rawDescData = file_shared_proto_admin_admin_proto_rawDesc
)

func file_shared_proto_admin_admin_proto_rawDescGZIP() []byte {
	file_shared_proto_admin_admin_proto_rawDescOnce.Do(func() {
		file_shared_proto_admin_admin_proto_rawDescData = protoimpl.X.CompressGZIP(file_shared_proto_admin_admin_proto_rawDescData)
	})
	return file_shared_proto_admin_admin_proto_rawDescData
}

var file_shared_proto_admin_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shared_proto_admin_admin_proto_goTypes = []interface{}{
	(*CollectReq)(nil),  // 0: admin.CollectReq
	(*CollectResp)(nil), // 1: admin.CollectResp
}
var file_shared_proto_admin_admin_proto_depIdxs = []int32{
	0, // 0: admin.AdminService.CollectPerformanceData:input_type -> admin.CollectReq
	1, // 1: admin.AdminService.CollectPerformanceData:output_type -> admin.CollectResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_proto_admin_admin_proto_init() }
func file_shared_proto_admin_admin_proto_init() {
	if File_shared_proto_admin_admin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shared_proto_admin_admin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_admin_admin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shared_proto_admin_admin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_admin_admin_proto_goTypes,
		DependencyIndexes: file_shared_proto_admin_admin_proto_depIdxs,
		MessageInfos:      file_shared_proto_admin_admin_proto_msgTypes,
	}.Build()
	File_shared_proto_admin_admin_proto = out.File
	file_shared_proto_admin_admin_proto_rawDesc = nil
	file_shared_proto_admin_admin_proto_goTypes = nil
	file_shared_proto_admin_admin_proto_depIdxs = nil
}
