// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v5.29.3
// source: shared/proto/colorgame/colorgame.proto

package colorgame

import (
	common "github.com/frankieli/game_product/shared/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED         EventType = 0
	EventType_EVENT_TYPE_ROUND_STARTED       EventType = 1
	EventType_EVENT_TYPE_BETTING_STARTED     EventType = 2
	EventType_EVENT_TYPE_DRAWING             EventType = 3
	EventType_EVENT_TYPE_RESULT              EventType = 4
	EventType_EVENT_TYPE_ROUND_ENDED         EventType = 5
	EventType_EVENT_TYPE_SETTLEMENT          EventType = 6
	EventType_EVENT_TYPE_SETTLEMENT_COMPLETE EventType = 7
	EventType_EVENT_TYPE_BET_PLACED          EventType = 8
	EventType_EVENT_TYPE_BET_ERROR           EventType = 9
	EventType_EVENT_TYPE_GAME_STATE          EventType = 10
	EventType_EVENT_TYPE_STATE_ERROR         EventType = 11
	EventType_EVENT_TYPE_MACHINE_STOPPED     EventType = 12
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "EVENT_TYPE_ROUND_STARTED",
		2:  "EVENT_TYPE_BETTING_STARTED",
		3:  "EVENT_TYPE_DRAWING",
		4:  "EVENT_TYPE_RESULT",
		5:  "EVENT_TYPE_ROUND_ENDED",
		6:  "EVENT_TYPE_SETTLEMENT",
		7:  "EVENT_TYPE_SETTLEMENT_COMPLETE",
		8:  "EVENT_TYPE_BET_PLACED",
		9:  "EVENT_TYPE_BET_ERROR",
		10: "EVENT_TYPE_GAME_STATE",
		11: "EVENT_TYPE_STATE_ERROR",
		12: "EVENT_TYPE_MACHINE_STOPPED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":         0,
		"EVENT_TYPE_ROUND_STARTED":       1,
		"EVENT_TYPE_BETTING_STARTED":     2,
		"EVENT_TYPE_DRAWING":             3,
		"EVENT_TYPE_RESULT":              4,
		"EVENT_TYPE_ROUND_ENDED":         5,
		"EVENT_TYPE_SETTLEMENT":          6,
		"EVENT_TYPE_SETTLEMENT_COMPLETE": 7,
		"EVENT_TYPE_BET_PLACED":          8,
		"EVENT_TYPE_BET_ERROR":           9,
		"EVENT_TYPE_GAME_STATE":          10,
		"EVENT_TYPE_STATE_ERROR":         11,
		"EVENT_TYPE_MACHINE_STOPPED":     12,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_colorgame_colorgame_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_shared_proto_colorgame_colorgame_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{0}
}

type PlaceBetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Color  string `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Amount int64  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *PlaceBetReq) Reset() {
	*x = PlaceBetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceBetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBetReq) ProtoMessage() {}

func (x *PlaceBetReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBetReq.ProtoReflect.Descriptor instead.
func (*PlaceBetReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceBetReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PlaceBetReq) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *PlaceBetReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PlaceBetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode common.ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=common.ErrorCode" json:"error_code,omitempty"`
	BetId     string           `protobuf:"bytes,2,opt,name=bet_id,json=betId,proto3" json:"bet_id,omitempty"`
	Error     string           `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *PlaceBetRsp) Reset() {
	*x = PlaceBetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceBetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBetRsp) ProtoMessage() {}

func (x *PlaceBetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBetRsp.ProtoReflect.Descriptor instead.
func (*PlaceBetRsp) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceBetRsp) GetErrorCode() common.ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return common.ErrorCode(0)
}

func (x *PlaceBetRsp) GetBetId() string {
	if x != nil {
		return x.BetId
	}
	return ""
}

func (x *PlaceBetRsp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetStateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetStateReq) Reset() {
	*x = GetStateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateReq) ProtoMessage() {}

func (x *GetStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateReq.ProtoReflect.Descriptor instead.
func (*GetStateReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{2}
}

func (x *GetStateReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetStateRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode common.ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=common.ErrorCode" json:"error_code,omitempty"`
	StateJson []byte           `protobuf:"bytes,2,opt,name=state_json,json=stateJson,proto3" json:"state_json,omitempty"`
}

func (x *GetStateRsp) Reset() {
	*x = GetStateRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStateRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRsp) ProtoMessage() {}

func (x *GetStateRsp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRsp.ProtoReflect.Descriptor instead.
func (*GetStateRsp) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{3}
}

func (x *GetStateRsp) GetErrorCode() common.ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return common.ErrorCode(0)
}

func (x *GetStateRsp) GetStateJson() []byte {
	if x != nil {
		return x.StateJson
	}
	return nil
}

type RecordBetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoundId string `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	UserId  int64  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Color   string `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Amount  int64  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *RecordBetReq) Reset() {
	*x = RecordBetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordBetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordBetReq) ProtoMessage() {}

func (x *RecordBetReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordBetReq.ProtoReflect.Descriptor instead.
func (*RecordBetReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{4}
}

func (x *RecordBetReq) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *RecordBetReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RecordBetReq) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *RecordBetReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type RecordBetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode common.ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=common.ErrorCode" json:"error_code,omitempty"`
	Error     string           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *RecordBetRsp) Reset() {
	*x = RecordBetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordBetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordBetRsp) ProtoMessage() {}

func (x *RecordBetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordBetRsp.ProtoReflect.Descriptor instead.
func (*RecordBetRsp) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{5}
}

func (x *RecordBetRsp) GetErrorCode() common.ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return common.ErrorCode(0)
}

func (x *RecordBetRsp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetCurrentRoundReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetCurrentRoundReq) Reset() {
	*x = GetCurrentRoundReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCurrentRoundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentRoundReq) ProtoMessage() {}

func (x *GetCurrentRoundReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentRoundReq.ProtoReflect.Descriptor instead.
func (*GetCurrentRoundReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{6}
}

func (x *GetCurrentRoundReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PlayerBet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Color  string `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	Amount int64  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *PlayerBet) Reset() {
	*x = PlayerBet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerBet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBet) ProtoMessage() {}

func (x *PlayerBet) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBet.ProtoReflect.Descriptor instead.
func (*PlayerBet) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerBet) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *PlayerBet) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetCurrentRoundRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode           common.ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=common.ErrorCode" json:"error_code,omitempty"`
	RoundId             string           `protobuf:"bytes,2,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	State               string           `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	BettingEndTimestamp int64            `protobuf:"varint,4,opt,name=betting_end_timestamp,json=bettingEndTimestamp,proto3" json:"betting_end_timestamp,omitempty"`
	PlayerBets          []*PlayerBet     `protobuf:"bytes,5,rep,name=player_bets,json=playerBets,proto3" json:"player_bets,omitempty"`
}

func (x *GetCurrentRoundRsp) Reset() {
	*x = GetCurrentRoundRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCurrentRoundRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentRoundRsp) ProtoMessage() {}

func (x *GetCurrentRoundRsp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentRoundRsp.ProtoReflect.Descriptor instead.
func (*GetCurrentRoundRsp) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{8}
}

func (x *GetCurrentRoundRsp) GetErrorCode() common.ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return common.ErrorCode(0)
}

func (x *GetCurrentRoundRsp) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *GetCurrentRoundRsp) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetCurrentRoundRsp) GetBettingEndTimestamp() int64 {
	if x != nil {
		return x.BettingEndTimestamp
	}
	return 0
}

func (x *GetCurrentRoundRsp) GetPlayerBets() []*PlayerBet {
	if x != nil {
		return x.PlayerBets
	}
	return nil
}

type SubscribeEventsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubscribeEventsReq) Reset() {
	*x = SubscribeEventsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeEventsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsReq) ProtoMessage() {}

func (x *SubscribeEventsReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsReq.ProtoReflect.Descriptor instead.
func (*SubscribeEventsReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{9}
}

type GameEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      EventType `protobuf:"varint,1,opt,name=type,proto3,enum=colorgame.EventType" json:"type,omitempty"`
	RoundId   string    `protobuf:"bytes,2,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	Data      string    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp int64     `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{10}
}

func (x *GameEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *GameEvent) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *GameEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *GameEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_shared_proto_colorgame_colorgame_proto protoreflect.FileDescriptor

var file_shared_proto_colorgame_colorgame_proto_rawDesc = []byte{
	0x0a, 0x26, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x67,
	0x61, 0x6d, 0x65, 0x1a, 0x20, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x6c, 0x0a, 0x0b, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x42, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x0a, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x15, 0x0a, 0x06,
	0x62, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x65,
	0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x26, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x5e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x73, 0x70,
	0x12, 0x30, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x6a, 0x73, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x4a, 0x73, 0x6f,
	0x6e, 0x22, 0x70, 0x0a, 0x0c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x56, 0x0a, 0x0c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x65, 0x74,
	0x52, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2d, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x09, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x42, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xe2, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x0a,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x32, 0x0a, 0x15, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x64, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13,
	0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x35, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x62, 0x65,
	0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x72,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x65, 0x74, 0x52, 0x0a,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x65, 0x74, 0x73, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x22, 0x82, 0x01, 0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x28,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x75, 0x6e,
	0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x75, 0x6e,
	0x64, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2a, 0xfb, 0x02, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x1c, 0x0a, 0x18, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x4f,
	0x55, 0x4e, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x1e, 0x0a,
	0x1a, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x42, 0x45, 0x54, 0x54,
	0x49, 0x4e, 0x47, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x16, 0x0a,
	0x12, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x52, 0x41, 0x57,
	0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x10, 0x04, 0x12, 0x1a, 0x0a, 0x16,
	0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x4f, 0x55, 0x4e, 0x44,
	0x5f, 0x45, 0x4e, 0x44, 0x45, 0x44, 0x10, 0x05, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x56, 0x45, 0x4e,
	0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x45, 0x54, 0x54, 0x4c, 0x45, 0x4d, 0x45, 0x4e,
	0x54, 0x10, 0x06, 0x12, 0x22, 0x0a, 0x1e, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x53, 0x45, 0x54, 0x54, 0x4c, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x43, 0x4f, 0x4d,
	0x50, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x07, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x56, 0x45, 0x4e, 0x54,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x42, 0x45, 0x54, 0x5f, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x44,
	0x10, 0x08, 0x12, 0x18, 0x0a, 0x14, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x42, 0x45, 0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x09, 0x12, 0x19, 0x0a, 0x15,
	0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x0a, 0x12, 0x1a, 0x0a, 0x16, 0x45, 0x56, 0x45, 0x4e, 0x54,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x0b, 0x12, 0x1e, 0x0a, 0x1a, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x4d, 0x41, 0x43, 0x48, 0x49, 0x4e, 0x45, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x45,
	0x44, 0x10, 0x0c, 0x32, 0x8a, 0x01, 0x0a, 0x10, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x47, 0x61, 0x6d,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x63,
	0x65, 0x42, 0x65, 0x74, 0x12, 0x16, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x65,
	0x74, 0x52, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x16, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x72,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x73, 0x70,
	0x32, 0xee, 0x01, 0x0a, 0x12, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x42, 0x65, 0x74, 0x12, 0x17, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e,
	0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x42, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x4f, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x72,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x52, 0x73, 0x70, 0x12, 0x48, 0x0a, 0x0f, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x6c,
	0x6f, 0x72, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x30,
	0x01, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x66, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x65, 0x6c, 0x69, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x67, 0x61, 0x6d, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shared_proto_colorgame_colorgame_proto_rawDescOnce sync.Once
	file_shared_proto_colorgame_colorgame_proto_rawDescData = file_shared_proto_colorgame_colorgame_proto_rawDesc
)

func file_shared_proto_colorgame_colorgame_proto_rawDescGZIP() []byte {
	file_shared_proto_colorgame_colorgame_proto_rawDescOnce.Do(func() {
		file_shared_proto_colorgame_colorgame_proto_rawDescData = protoimpl.X.CompressGZIP(file_shared_proto_colorgame_colorgame_proto_rawDescData)
	})
	return file_shared_proto_colorgame_colorgame_proto_rawDescData
}

var file_shared_proto_colorgame_colorgame_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_proto_colorgame_colorgame_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_shared_proto_colorgame_colorgame_proto_goTypes = []interface{}{
	(EventType)(0),             // 0: colorgame.EventType
	(*PlaceBetReq)(nil),        // 1: colorgame.PlaceBetReq
	(*PlaceBetRsp)(nil),        // 2: colorgame.PlaceBetRsp
	(*GetStateReq)(nil),        // 3: colorgame.GetStateReq
	(*GetStateRsp)(nil),        // 4: colorgame.GetStateRsp
	(*RecordBetReq)(nil),       // 5: colorgame.RecordBetReq
	(*RecordBetRsp)(nil),       // 6: colorgame.RecordBetRsp
	(*GetCurrentRoundReq)(nil), // 7: colorgame.GetCurrentRoundReq
	(*PlayerBet)(nil),          // 8: colorgame.PlayerBet
	(*GetCurrentRoundRsp)(nil), // 9: colorgame.GetCurrentRoundRsp
	(*SubscribeEventsReq)(nil), // 10: colorgame.SubscribeEventsReq
	(*GameEvent)(nil),          // 11: colorgame.GameEvent
	(common.ErrorCode)(0),      // 12: common.ErrorCode
}
var file_shared_proto_colorgame_colorgame_proto_depIdxs = []int32{
	12, // 0: colorgame.PlaceBetRsp.error_code:type_name -> common.ErrorCode
	12, // 1: colorgame.GetStateRsp.error_code:type_name -> common.ErrorCode
	12, // 2: colorgame.RecordBetRsp.error_code:type_name -> common.ErrorCode
	12, // 3: colorgame.GetCurrentRoundRsp.error_code:type_name -> common.ErrorCode
	8,  // 4: colorgame.GetCurrentRoundRsp.player_bets:type_name -> colorgame.PlayerBet
	0,  // 5: colorgame.GameEvent.type:type_name -> colorgame.EventType
	1,  // 6: colorgame.ColorGameService.PlaceBet:input_type -> colorgame.PlaceBetReq
	3,  // 7: colorgame.ColorGameService.GetState:input_type -> colorgame.GetStateReq
	5,  // 8: colorgame.GameMachineService.RecordBet:input_type -> colorgame.RecordBetReq
	7,  // 9: colorgame.GameMachineService.GetCurrentRound:input_type -> colorgame.GetCurrentRoundReq
	10, // 10: colorgame.GameMachineService.SubscribeEvents:input_type -> colorgame.SubscribeEventsReq
	2,  // 11: colorgame.ColorGameService.PlaceBet:output_type -> colorgame.PlaceBetRsp
	4,  // 12: colorgame.ColorGameService.GetState:output_type -> colorgame.GetStateRsp
	6,  // 13: colorgame.GameMachineService.RecordBet:output_type -> colorgame.RecordBetRsp
	9,  // 14: colorgame.GameMachineService.GetCurrentRound:output_type -> colorgame.GetCurrentRoundRsp
	11, // 15: colorgame.GameMachineService.SubscribeEvents:output_type -> colorgame.GameEvent
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_shared_proto_colorgame_colorgame_proto_init() }
func file_shared_proto_colorgame_colorgame_proto_init() {
	if File_shared_proto_colorgame_colorgame_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shared_proto_colorgame_colorgame_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceBetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceBetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStateRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordBetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordBetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCurrentRoundReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerBet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCurrentRoundRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeEventsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shared_proto_colorgame_colorgame_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_shared_proto_colorgame_colorgame_proto_goTypes,
		DependencyIndexes: file_shared_proto_colorgame_colorgame_proto_depIdxs,
		EnumInfos:         file_shared_proto_colorgame_colorgame_proto_enumTypes,
		MessageInfos:      file_shared_proto_colorgame_colorgame_proto_msgTypes,
	}.Build()
	File_shared_proto_colorgame_colorgame_proto = out.File
	file_shared_proto_colorgame_colorgame_proto_rawDesc = nil
	file_shared_proto_colorgame_colorgame_proto_goTypes = nil
	file_shared_proto_colorgame_colorgame_proto_depIdxs = nil
}
