// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: shared/proto/colorgame/colorgame.proto

package colorgame

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ColorGameServiceClient is the client API for ColorGameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ColorGameServiceClient interface {
	// PlaceBet handles placing a bet
	PlaceBet(ctx context.Context, in *ColorGamePlaceBetReq, opts ...grpc.CallOption) (*ColorGamePlaceBetRsp, error)
	// GetState returns the current game state
	GetState(ctx context.Context, in *ColorGameGetStateReq, opts ...grpc.CallOption) (*ColorGameGetStateRsp, error)
}

type colorGameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewColorGameServiceClient(cc grpc.ClientConnInterface) ColorGameServiceClient {
	return &colorGameServiceClient{cc}
}

func (c *colorGameServiceClient) PlaceBet(ctx context.Context, in *ColorGamePlaceBetReq, opts ...grpc.CallOption) (*ColorGamePlaceBetRsp, error) {
	out := new(ColorGamePlaceBetRsp)
	err := c.cc.Invoke(ctx, "/colorgame.ColorGameService/PlaceBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colorGameServiceClient) GetState(ctx context.Context, in *ColorGameGetStateReq, opts ...grpc.CallOption) (*ColorGameGetStateRsp, error) {
	out := new(ColorGameGetStateRsp)
	err := c.cc.Invoke(ctx, "/colorgame.ColorGameService/GetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ColorGameServiceServer is the server API for ColorGameService service.
// All implementations must embed UnimplementedColorGameServiceServer
// for forward compatibility
type ColorGameServiceServer interface {
	// PlaceBet handles placing a bet
	PlaceBet(context.Context, *ColorGamePlaceBetReq) (*ColorGamePlaceBetRsp, error)
	// GetState returns the current game state
	GetState(context.Context, *ColorGameGetStateReq) (*ColorGameGetStateRsp, error)
	mustEmbedUnimplementedColorGameServiceServer()
}

// UnimplementedColorGameServiceServer must be embedded to have forward compatible implementations.
type UnimplementedColorGameServiceServer struct {
}

func (UnimplementedColorGameServiceServer) PlaceBet(context.Context, *ColorGamePlaceBetReq) (*ColorGamePlaceBetRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceBet not implemented")
}
func (UnimplementedColorGameServiceServer) GetState(context.Context, *ColorGameGetStateReq) (*ColorGameGetStateRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedColorGameServiceServer) mustEmbedUnimplementedColorGameServiceServer() {}

// UnsafeColorGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ColorGameServiceServer will
// result in compilation errors.
type UnsafeColorGameServiceServer interface {
	mustEmbedUnimplementedColorGameServiceServer()
}

func RegisterColorGameServiceServer(s grpc.ServiceRegistrar, srv ColorGameServiceServer) {
	s.RegisterService(&ColorGameService_ServiceDesc, srv)
}

func _ColorGameService_PlaceBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ColorGamePlaceBetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColorGameServiceServer).PlaceBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/colorgame.ColorGameService/PlaceBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColorGameServiceServer).PlaceBet(ctx, req.(*ColorGamePlaceBetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColorGameService_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ColorGameGetStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColorGameServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/colorgame.ColorGameService/GetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColorGameServiceServer).GetState(ctx, req.(*ColorGameGetStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ColorGameService_ServiceDesc is the grpc.ServiceDesc for ColorGameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ColorGameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "colorgame.ColorGameService",
	HandlerType: (*ColorGameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlaceBet",
			Handler:    _ColorGameService_PlaceBet_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _ColorGameService_GetState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shared/proto/colorgame/colorgame.proto",
}
