// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v5.29.3
// source: shared/proto/colorgame/colorgame.proto

package colorgame

import (
	common "github.com/frankieli/game_product/shared/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ColorGameEventType int32

const (
	ColorGameEventType_EVENT_TYPE_UNSPECIFIED         ColorGameEventType = 0
	ColorGameEventType_EVENT_TYPE_ROUND_STARTED       ColorGameEventType = 1
	ColorGameEventType_EVENT_TYPE_BETTING_STARTED     ColorGameEventType = 2
	ColorGameEventType_EVENT_TYPE_DRAWING             ColorGameEventType = 3
	ColorGameEventType_EVENT_TYPE_RESULT              ColorGameEventType = 4
	ColorGameEventType_EVENT_TYPE_ROUND_ENDED         ColorGameEventType = 5
	ColorGameEventType_EVENT_TYPE_SETTLEMENT          ColorGameEventType = 6
	ColorGameEventType_EVENT_TYPE_SETTLEMENT_COMPLETE ColorGameEventType = 7
	ColorGameEventType_EVENT_TYPE_BET_PLACED          ColorGameEventType = 8
	ColorGameEventType_EVENT_TYPE_BET_ERROR           ColorGameEventType = 9
	ColorGameEventType_EVENT_TYPE_GAME_STATE          ColorGameEventType = 10
	ColorGameEventType_EVENT_TYPE_STATE_ERROR         ColorGameEventType = 11
	ColorGameEventType_EVENT_TYPE_MACHINE_STOPPED     ColorGameEventType = 12
)

// Enum value maps for ColorGameEventType.
var (
	ColorGameEventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "EVENT_TYPE_ROUND_STARTED",
		2:  "EVENT_TYPE_BETTING_STARTED",
		3:  "EVENT_TYPE_DRAWING",
		4:  "EVENT_TYPE_RESULT",
		5:  "EVENT_TYPE_ROUND_ENDED",
		6:  "EVENT_TYPE_SETTLEMENT",
		7:  "EVENT_TYPE_SETTLEMENT_COMPLETE",
		8:  "EVENT_TYPE_BET_PLACED",
		9:  "EVENT_TYPE_BET_ERROR",
		10: "EVENT_TYPE_GAME_STATE",
		11: "EVENT_TYPE_STATE_ERROR",
		12: "EVENT_TYPE_MACHINE_STOPPED",
	}
	ColorGameEventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":         0,
		"EVENT_TYPE_ROUND_STARTED":       1,
		"EVENT_TYPE_BETTING_STARTED":     2,
		"EVENT_TYPE_DRAWING":             3,
		"EVENT_TYPE_RESULT":              4,
		"EVENT_TYPE_ROUND_ENDED":         5,
		"EVENT_TYPE_SETTLEMENT":          6,
		"EVENT_TYPE_SETTLEMENT_COMPLETE": 7,
		"EVENT_TYPE_BET_PLACED":          8,
		"EVENT_TYPE_BET_ERROR":           9,
		"EVENT_TYPE_GAME_STATE":          10,
		"EVENT_TYPE_STATE_ERROR":         11,
		"EVENT_TYPE_MACHINE_STOPPED":     12,
	}
)

func (x ColorGameEventType) Enum() *ColorGameEventType {
	p := new(ColorGameEventType)
	*p = x
	return p
}

func (x ColorGameEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColorGameEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_colorgame_colorgame_proto_enumTypes[0].Descriptor()
}

func (ColorGameEventType) Type() protoreflect.EnumType {
	return &file_shared_proto_colorgame_colorgame_proto_enumTypes[0]
}

func (x ColorGameEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColorGameEventType.Descriptor instead.
func (ColorGameEventType) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{0}
}

// CommandType defines all WebSocket command types
// All commands follow PascalCase naming convention
type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED CommandType = 0
	// Client -> Server (REQ)
	CommandType_COMMAND_TYPE_PLACE_BET_REQ CommandType = 1
	CommandType_COMMAND_TYPE_GET_STATE_REQ CommandType = 2
	// Server -> Client (RSP)
	CommandType_COMMAND_TYPE_PLACE_BET_RSP CommandType = 3
	CommandType_COMMAND_TYPE_GET_STATE_RSP CommandType = 4
	// Server -> Client (BRC - Broadcast)
	CommandType_COMMAND_TYPE_COLOR_GAME_ROUND_STATE_BRC CommandType = 5
	CommandType_COMMAND_TYPE_RESULT_BRC                 CommandType = 6
	CommandType_COMMAND_TYPE_SETTLEMENT_BRC             CommandType = 7
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "COMMAND_TYPE_PLACE_BET_REQ",
		2: "COMMAND_TYPE_GET_STATE_REQ",
		3: "COMMAND_TYPE_PLACE_BET_RSP",
		4: "COMMAND_TYPE_GET_STATE_RSP",
		5: "COMMAND_TYPE_COLOR_GAME_ROUND_STATE_BRC",
		6: "COMMAND_TYPE_RESULT_BRC",
		7: "COMMAND_TYPE_SETTLEMENT_BRC",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED":                0,
		"COMMAND_TYPE_PLACE_BET_REQ":              1,
		"COMMAND_TYPE_GET_STATE_REQ":              2,
		"COMMAND_TYPE_PLACE_BET_RSP":              3,
		"COMMAND_TYPE_GET_STATE_RSP":              4,
		"COMMAND_TYPE_COLOR_GAME_ROUND_STATE_BRC": 5,
		"COMMAND_TYPE_RESULT_BRC":                 6,
		"COMMAND_TYPE_SETTLEMENT_BRC":             7,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_colorgame_colorgame_proto_enumTypes[1].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_shared_proto_colorgame_colorgame_proto_enumTypes[1]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{1}
}

type ColorGamePlaceBetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Color  string `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Amount int64  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *ColorGamePlaceBetReq) Reset() {
	*x = ColorGamePlaceBetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColorGamePlaceBetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorGamePlaceBetReq) ProtoMessage() {}

func (x *ColorGamePlaceBetReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorGamePlaceBetReq.ProtoReflect.Descriptor instead.
func (*ColorGamePlaceBetReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{0}
}

func (x *ColorGamePlaceBetReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ColorGamePlaceBetReq) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ColorGamePlaceBetReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ColorGamePlaceBetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode common.ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=common.ErrorCode" json:"error_code,omitempty"`
	BetId     string           `protobuf:"bytes,2,opt,name=bet_id,json=betId,proto3" json:"bet_id,omitempty"`
	Error     string           `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ColorGamePlaceBetRsp) Reset() {
	*x = ColorGamePlaceBetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColorGamePlaceBetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorGamePlaceBetRsp) ProtoMessage() {}

func (x *ColorGamePlaceBetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorGamePlaceBetRsp.ProtoReflect.Descriptor instead.
func (*ColorGamePlaceBetRsp) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{1}
}

func (x *ColorGamePlaceBetRsp) GetErrorCode() common.ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return common.ErrorCode(0)
}

func (x *ColorGamePlaceBetRsp) GetBetId() string {
	if x != nil {
		return x.BetId
	}
	return ""
}

func (x *ColorGamePlaceBetRsp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ColorGameGetStateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ColorGameGetStateReq) Reset() {
	*x = ColorGameGetStateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColorGameGetStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorGameGetStateReq) ProtoMessage() {}

func (x *ColorGameGetStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorGameGetStateReq.ProtoReflect.Descriptor instead.
func (*ColorGameGetStateReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{2}
}

func (x *ColorGameGetStateReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ColorGameGetStateRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode common.ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=common.ErrorCode" json:"error_code,omitempty"`
	StateJson []byte           `protobuf:"bytes,2,opt,name=state_json,json=stateJson,proto3" json:"state_json,omitempty"`
}

func (x *ColorGameGetStateRsp) Reset() {
	*x = ColorGameGetStateRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColorGameGetStateRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorGameGetStateRsp) ProtoMessage() {}

func (x *ColorGameGetStateRsp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorGameGetStateRsp.ProtoReflect.Descriptor instead.
func (*ColorGameGetStateRsp) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{3}
}

func (x *ColorGameGetStateRsp) GetErrorCode() common.ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return common.ErrorCode(0)
}

func (x *ColorGameGetStateRsp) GetStateJson() []byte {
	if x != nil {
		return x.StateJson
	}
	return nil
}

type ColorGameRecordBetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoundId string `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	UserId  int64  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Color   string `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Amount  int64  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *ColorGameRecordBetReq) Reset() {
	*x = ColorGameRecordBetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColorGameRecordBetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorGameRecordBetReq) ProtoMessage() {}

func (x *ColorGameRecordBetReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorGameRecordBetReq.ProtoReflect.Descriptor instead.
func (*ColorGameRecordBetReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{4}
}

func (x *ColorGameRecordBetReq) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *ColorGameRecordBetReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ColorGameRecordBetReq) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ColorGameRecordBetReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ColorGameRecordBetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode common.ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=common.ErrorCode" json:"error_code,omitempty"`
	Error     string           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ColorGameRecordBetRsp) Reset() {
	*x = ColorGameRecordBetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColorGameRecordBetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorGameRecordBetRsp) ProtoMessage() {}

func (x *ColorGameRecordBetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorGameRecordBetRsp.ProtoReflect.Descriptor instead.
func (*ColorGameRecordBetRsp) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{5}
}

func (x *ColorGameRecordBetRsp) GetErrorCode() common.ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return common.ErrorCode(0)
}

func (x *ColorGameRecordBetRsp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ColorGameGetCurrentRoundReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ColorGameGetCurrentRoundReq) Reset() {
	*x = ColorGameGetCurrentRoundReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColorGameGetCurrentRoundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorGameGetCurrentRoundReq) ProtoMessage() {}

func (x *ColorGameGetCurrentRoundReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorGameGetCurrentRoundReq.ProtoReflect.Descriptor instead.
func (*ColorGameGetCurrentRoundReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{6}
}

func (x *ColorGameGetCurrentRoundReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ColorGamePlayerBet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Color  string `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	Amount int64  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *ColorGamePlayerBet) Reset() {
	*x = ColorGamePlayerBet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColorGamePlayerBet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorGamePlayerBet) ProtoMessage() {}

func (x *ColorGamePlayerBet) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorGamePlayerBet.ProtoReflect.Descriptor instead.
func (*ColorGamePlayerBet) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{7}
}

func (x *ColorGamePlayerBet) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ColorGamePlayerBet) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ColorGameGetCurrentRoundRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode           common.ErrorCode      `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=common.ErrorCode" json:"error_code,omitempty"`
	RoundId             string                `protobuf:"bytes,2,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	State               string                `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	BettingEndTimestamp int64                 `protobuf:"varint,4,opt,name=betting_end_timestamp,json=bettingEndTimestamp,proto3" json:"betting_end_timestamp,omitempty"`
	PlayerBets          []*ColorGamePlayerBet `protobuf:"bytes,5,rep,name=player_bets,json=playerBets,proto3" json:"player_bets,omitempty"`
	LeftTime            int64                 `protobuf:"varint,6,opt,name=left_time,json=leftTime,proto3" json:"left_time,omitempty"`
}

func (x *ColorGameGetCurrentRoundRsp) Reset() {
	*x = ColorGameGetCurrentRoundRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColorGameGetCurrentRoundRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorGameGetCurrentRoundRsp) ProtoMessage() {}

func (x *ColorGameGetCurrentRoundRsp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorGameGetCurrentRoundRsp.ProtoReflect.Descriptor instead.
func (*ColorGameGetCurrentRoundRsp) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{8}
}

func (x *ColorGameGetCurrentRoundRsp) GetErrorCode() common.ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return common.ErrorCode(0)
}

func (x *ColorGameGetCurrentRoundRsp) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *ColorGameGetCurrentRoundRsp) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ColorGameGetCurrentRoundRsp) GetBettingEndTimestamp() int64 {
	if x != nil {
		return x.BettingEndTimestamp
	}
	return 0
}

func (x *ColorGameGetCurrentRoundRsp) GetPlayerBets() []*ColorGamePlayerBet {
	if x != nil {
		return x.PlayerBets
	}
	return nil
}

func (x *ColorGameGetCurrentRoundRsp) GetLeftTime() int64 {
	if x != nil {
		return x.LeftTime
	}
	return 0
}

type ColorGameSubscribeEventsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ColorGameSubscribeEventsReq) Reset() {
	*x = ColorGameSubscribeEventsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColorGameSubscribeEventsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorGameSubscribeEventsReq) ProtoMessage() {}

func (x *ColorGameSubscribeEventsReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorGameSubscribeEventsReq.ProtoReflect.Descriptor instead.
func (*ColorGameSubscribeEventsReq) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{9}
}

type ColorGameEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type                ColorGameEventType `protobuf:"varint,1,opt,name=type,proto3,enum=colorgame.ColorGameEventType" json:"type,omitempty"`
	RoundId             string             `protobuf:"bytes,2,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	Data                string             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // JSON string containing event-specific data
	Timestamp           int64              `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LeftTime            int64              `protobuf:"varint,5,opt,name=left_time,json=leftTime,proto3" json:"left_time,omitempty"`
	BettingEndTimestamp int64              `protobuf:"varint,6,opt,name=betting_end_timestamp,json=bettingEndTimestamp,proto3" json:"betting_end_timestamp,omitempty"`
}

func (x *ColorGameEvent) Reset() {
	*x = ColorGameEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColorGameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorGameEvent) ProtoMessage() {}

func (x *ColorGameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorGameEvent.ProtoReflect.Descriptor instead.
func (*ColorGameEvent) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{10}
}

func (x *ColorGameEvent) GetType() ColorGameEventType {
	if x != nil {
		return x.Type
	}
	return ColorGameEventType_EVENT_TYPE_UNSPECIFIED
}

func (x *ColorGameEvent) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *ColorGameEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ColorGameEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ColorGameEvent) GetLeftTime() int64 {
	if x != nil {
		return x.LeftTime
	}
	return 0
}

func (x *ColorGameEvent) GetBettingEndTimestamp() int64 {
	if x != nil {
		return x.BettingEndTimestamp
	}
	return 0
}

type ColorGameRoundStateBRC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoundId             string `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	State               string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	BettingEndTimestamp int64  `protobuf:"varint,3,opt,name=betting_end_timestamp,json=bettingEndTimestamp,proto3" json:"betting_end_timestamp,omitempty"`
	LeftTime            int64  `protobuf:"varint,4,opt,name=left_time,json=leftTime,proto3" json:"left_time,omitempty"`
}

func (x *ColorGameRoundStateBRC) Reset() {
	*x = ColorGameRoundStateBRC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColorGameRoundStateBRC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorGameRoundStateBRC) ProtoMessage() {}

func (x *ColorGameRoundStateBRC) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorGameRoundStateBRC.ProtoReflect.Descriptor instead.
func (*ColorGameRoundStateBRC) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{11}
}

func (x *ColorGameRoundStateBRC) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *ColorGameRoundStateBRC) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ColorGameRoundStateBRC) GetBettingEndTimestamp() int64 {
	if x != nil {
		return x.BettingEndTimestamp
	}
	return 0
}

func (x *ColorGameRoundStateBRC) GetLeftTime() int64 {
	if x != nil {
		return x.LeftTime
	}
	return 0
}

// ColorGameBetConfirmation is sent to user after a bet is placed
type ColorGameBetConfirmation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoundId  string `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	BetId    string `protobuf:"bytes,2,opt,name=bet_id,json=betId,proto3" json:"bet_id,omitempty"`
	UserId   int64  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Color    string `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Amount   int64  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	IsUpdate bool   `protobuf:"varint,6,opt,name=is_update,json=isUpdate,proto3" json:"is_update,omitempty"` // true if this was an accumulation of existing bet
}

func (x *ColorGameBetConfirmation) Reset() {
	*x = ColorGameBetConfirmation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColorGameBetConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorGameBetConfirmation) ProtoMessage() {}

func (x *ColorGameBetConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorGameBetConfirmation.ProtoReflect.Descriptor instead.
func (*ColorGameBetConfirmation) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{12}
}

func (x *ColorGameBetConfirmation) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *ColorGameBetConfirmation) GetBetId() string {
	if x != nil {
		return x.BetId
	}
	return ""
}

func (x *ColorGameBetConfirmation) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ColorGameBetConfirmation) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ColorGameBetConfirmation) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ColorGameBetConfirmation) GetIsUpdate() bool {
	if x != nil {
		return x.IsUpdate
	}
	return false
}

// ColorGameSettlementBRC is sent to users after round settlement
// 有下注和無下注的玩家收到的欄位不同
type ColorGameSettlementBRC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoundId      string `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	WinningColor string `protobuf:"bytes,2,opt,name=winning_color,json=winningColor,proto3" json:"winning_color,omitempty"`
	// 以下欄位只有下注的玩家才有值
	BetId     string `protobuf:"bytes,3,opt,name=bet_id,json=betId,proto3" json:"bet_id,omitempty"`              // 下注 ID（無下注時為空）
	BetColor  string `protobuf:"bytes,4,opt,name=bet_color,json=betColor,proto3" json:"bet_color,omitempty"`     // 下注顏色（無下注時為空）
	BetAmount int64  `protobuf:"varint,5,opt,name=bet_amount,json=betAmount,proto3" json:"bet_amount,omitempty"` // 下注金額（無下注時為 0）
	WinAmount int64  `protobuf:"varint,6,opt,name=win_amount,json=winAmount,proto3" json:"win_amount,omitempty"` // 贏得金額（無下注或輸了時為 0）
	IsWinner  bool   `protobuf:"varint,7,opt,name=is_winner,json=isWinner,proto3" json:"is_winner,omitempty"`    // 是否贏家（無下注時為 false）
}

func (x *ColorGameSettlementBRC) Reset() {
	*x = ColorGameSettlementBRC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColorGameSettlementBRC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorGameSettlementBRC) ProtoMessage() {}

func (x *ColorGameSettlementBRC) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_colorgame_colorgame_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorGameSettlementBRC.ProtoReflect.Descriptor instead.
func (*ColorGameSettlementBRC) Descriptor() ([]byte, []int) {
	return file_shared_proto_colorgame_colorgame_proto_rawDescGZIP(), []int{13}
}

func (x *ColorGameSettlementBRC) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *ColorGameSettlementBRC) GetWinningColor() string {
	if x != nil {
		return x.WinningColor
	}
	return ""
}

func (x *ColorGameSettlementBRC) GetBetId() string {
	if x != nil {
		return x.BetId
	}
	return ""
}

func (x *ColorGameSettlementBRC) GetBetColor() string {
	if x != nil {
		return x.BetColor
	}
	return ""
}

func (x *ColorGameSettlementBRC) GetBetAmount() int64 {
	if x != nil {
		return x.BetAmount
	}
	return 0
}

func (x *ColorGameSettlementBRC) GetWinAmount() int64 {
	if x != nil {
		return x.WinAmount
	}
	return 0
}

func (x *ColorGameSettlementBRC) GetIsWinner() bool {
	if x != nil {
		return x.IsWinner
	}
	return false
}

var File_shared_proto_colorgame_colorgame_proto protoreflect.FileDescriptor

var file_shared_proto_colorgame_colorgame_proto_rawDesc = []byte{
	0x0a, 0x26, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x67,
	0x61, 0x6d, 0x65, 0x1a, 0x20, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x14, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x47, 0x61,
	0x6d, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x75, 0x0a, 0x14, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x47, 0x61, 0x6d,
	0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x0a,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x15,
	0x0a, 0x06, 0x62, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x62, 0x65, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2f, 0x0a, 0x14, 0x43,
	0x6f, 0x6c, 0x6f, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x67, 0x0a, 0x14,
	0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f,
	0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x79, 0x0a, 0x15, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x47, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x19,
	0x0a, 0x08, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x5f, 0x0a, 0x15, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x42, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x0a, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x36, 0x0a, 0x1b, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x47, 0x65,
	0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x42, 0x0a, 0x12, 0x43, 0x6f, 0x6c,
	0x6f, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x65, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x91, 0x02,
	0x0a, 0x1b, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x47, 0x65, 0x74, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x73, 0x70, 0x12, 0x30, 0x0a,
	0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x32, 0x0a, 0x15, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x64, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x13, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x12, 0x3e, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x62,
	0x65, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x65, 0x74, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x42, 0x65, 0x74, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x66, 0x74, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6c, 0x65, 0x66, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x1d, 0x0a, 0x1b, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x22, 0xe1, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x31, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x43, 0x6f,
	0x6c, 0x6f, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x66, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6c, 0x65, 0x66, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x32, 0x0a, 0x15, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x64, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x13, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x22, 0x9a, 0x01, 0x0a, 0x16, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x47, 0x61,
	0x6d, 0x65, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42, 0x52, 0x43, 0x12,
	0x19, 0x0a, 0x08, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x32, 0x0a, 0x15, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x64, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x13, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x66, 0x74, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6c, 0x65, 0x66, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0xb0, 0x01, 0x0a, 0x18, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x42,
	0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19,
	0x0a, 0x08, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x65, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x65, 0x74, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c,
	0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x22, 0xe7, 0x01, 0x0a, 0x16, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x52, 0x43, 0x12,
	0x19, 0x0a, 0x08, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x77, 0x69,
	0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x77, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12,
	0x15, 0x0a, 0x06, 0x62, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x62, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x65, 0x74, 0x5f, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x65, 0x74, 0x43, 0x6f,
	0x6c, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x65, 0x74, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x62, 0x65, 0x74, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x69, 0x6e, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x77, 0x69, 0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2a, 0x84,
	0x03, 0x0a, 0x12, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x1c, 0x0a, 0x18, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x52, 0x4f, 0x55, 0x4e, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12,
	0x1e, 0x0a, 0x1a, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x42, 0x45,
	0x54, 0x54, 0x49, 0x4e, 0x47, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12,
	0x16, 0x0a, 0x12, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x52,
	0x41, 0x57, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x56, 0x45, 0x4e, 0x54,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x10, 0x04, 0x12, 0x1a,
	0x0a, 0x16, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x4f, 0x55,
	0x4e, 0x44, 0x5f, 0x45, 0x4e, 0x44, 0x45, 0x44, 0x10, 0x05, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x56,
	0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x45, 0x54, 0x54, 0x4c, 0x45, 0x4d,
	0x45, 0x4e, 0x54, 0x10, 0x06, 0x12, 0x22, 0x0a, 0x1e, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x53, 0x45, 0x54, 0x54, 0x4c, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x43,
	0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x07, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x56, 0x45,
	0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x42, 0x45, 0x54, 0x5f, 0x50, 0x4c, 0x41, 0x43,
	0x45, 0x44, 0x10, 0x08, 0x12, 0x18, 0x0a, 0x14, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x42, 0x45, 0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x09, 0x12, 0x19,
	0x0a, 0x15, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x41, 0x4d,
	0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x0a, 0x12, 0x1a, 0x0a, 0x16, 0x45, 0x56, 0x45,
	0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x0b, 0x12, 0x1e, 0x0a, 0x1a, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x4d, 0x41, 0x43, 0x48, 0x49, 0x4e, 0x45, 0x5f, 0x53, 0x54, 0x4f, 0x50,
	0x50, 0x45, 0x44, 0x10, 0x0c, 0x2a, 0x96, 0x02, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x5f, 0x42, 0x45, 0x54, 0x5f, 0x52, 0x45,
	0x51, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45,
	0x51, 0x10, 0x02, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x5f, 0x42, 0x45, 0x54, 0x5f, 0x52, 0x53,
	0x50, 0x10, 0x03, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x53,
	0x50, 0x10, 0x04, 0x12, 0x2b, 0x0a, 0x27, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x52,
	0x4f, 0x55, 0x4e, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x42, 0x52, 0x43, 0x10, 0x05,
	0x12, 0x1b, 0x0a, 0x17, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x42, 0x52, 0x43, 0x10, 0x06, 0x12, 0x1f, 0x0a,
	0x1b, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x45,
	0x54, 0x54, 0x4c, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x42, 0x52, 0x43, 0x10, 0x07, 0x32, 0xae,
	0x01, 0x0a, 0x10, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x65, 0x74, 0x12,
	0x1f, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x43, 0x6f, 0x6c, 0x6f,
	0x72, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x1f, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x43, 0x6f, 0x6c,
	0x6f, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x65, 0x74, 0x52, 0x73,
	0x70, 0x12, 0x4c, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x2e,
	0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x47,
	0x61, 0x6d, 0x65, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1f,
	0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72,
	0x47, 0x61, 0x6d, 0x65, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x73, 0x70, 0x42,
	0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x72,
	0x61, 0x6e, 0x6b, 0x69, 0x65, 0x6c, 0x69, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x67, 0x61, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_shared_proto_colorgame_colorgame_proto_rawDescOnce sync.Once
	file_shared_proto_colorgame_colorgame_proto_rawDescData = file_shared_proto_colorgame_colorgame_proto_rawDesc
)

func file_shared_proto_colorgame_colorgame_proto_rawDescGZIP() []byte {
	file_shared_proto_colorgame_colorgame_proto_rawDescOnce.Do(func() {
		file_shared_proto_colorgame_colorgame_proto_rawDescData = protoimpl.X.CompressGZIP(file_shared_proto_colorgame_colorgame_proto_rawDescData)
	})
	return file_shared_proto_colorgame_colorgame_proto_rawDescData
}

var file_shared_proto_colorgame_colorgame_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_shared_proto_colorgame_colorgame_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_shared_proto_colorgame_colorgame_proto_goTypes = []interface{}{
	(ColorGameEventType)(0),             // 0: colorgame.ColorGameEventType
	(CommandType)(0),                    // 1: colorgame.CommandType
	(*ColorGamePlaceBetReq)(nil),        // 2: colorgame.ColorGamePlaceBetReq
	(*ColorGamePlaceBetRsp)(nil),        // 3: colorgame.ColorGamePlaceBetRsp
	(*ColorGameGetStateReq)(nil),        // 4: colorgame.ColorGameGetStateReq
	(*ColorGameGetStateRsp)(nil),        // 5: colorgame.ColorGameGetStateRsp
	(*ColorGameRecordBetReq)(nil),       // 6: colorgame.ColorGameRecordBetReq
	(*ColorGameRecordBetRsp)(nil),       // 7: colorgame.ColorGameRecordBetRsp
	(*ColorGameGetCurrentRoundReq)(nil), // 8: colorgame.ColorGameGetCurrentRoundReq
	(*ColorGamePlayerBet)(nil),          // 9: colorgame.ColorGamePlayerBet
	(*ColorGameGetCurrentRoundRsp)(nil), // 10: colorgame.ColorGameGetCurrentRoundRsp
	(*ColorGameSubscribeEventsReq)(nil), // 11: colorgame.ColorGameSubscribeEventsReq
	(*ColorGameEvent)(nil),              // 12: colorgame.ColorGameEvent
	(*ColorGameRoundStateBRC)(nil),      // 13: colorgame.ColorGameRoundStateBRC
	(*ColorGameBetConfirmation)(nil),    // 14: colorgame.ColorGameBetConfirmation
	(*ColorGameSettlementBRC)(nil),      // 15: colorgame.ColorGameSettlementBRC
	(common.ErrorCode)(0),               // 16: common.ErrorCode
}
var file_shared_proto_colorgame_colorgame_proto_depIdxs = []int32{
	16, // 0: colorgame.ColorGamePlaceBetRsp.error_code:type_name -> common.ErrorCode
	16, // 1: colorgame.ColorGameGetStateRsp.error_code:type_name -> common.ErrorCode
	16, // 2: colorgame.ColorGameRecordBetRsp.error_code:type_name -> common.ErrorCode
	16, // 3: colorgame.ColorGameGetCurrentRoundRsp.error_code:type_name -> common.ErrorCode
	9,  // 4: colorgame.ColorGameGetCurrentRoundRsp.player_bets:type_name -> colorgame.ColorGamePlayerBet
	0,  // 5: colorgame.ColorGameEvent.type:type_name -> colorgame.ColorGameEventType
	2,  // 6: colorgame.ColorGameService.PlaceBet:input_type -> colorgame.ColorGamePlaceBetReq
	4,  // 7: colorgame.ColorGameService.GetState:input_type -> colorgame.ColorGameGetStateReq
	3,  // 8: colorgame.ColorGameService.PlaceBet:output_type -> colorgame.ColorGamePlaceBetRsp
	5,  // 9: colorgame.ColorGameService.GetState:output_type -> colorgame.ColorGameGetStateRsp
	8,  // [8:10] is the sub-list for method output_type
	6,  // [6:8] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_shared_proto_colorgame_colorgame_proto_init() }
func file_shared_proto_colorgame_colorgame_proto_init() {
	if File_shared_proto_colorgame_colorgame_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shared_proto_colorgame_colorgame_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColorGamePlaceBetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColorGamePlaceBetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColorGameGetStateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColorGameGetStateRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColorGameRecordBetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColorGameRecordBetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColorGameGetCurrentRoundReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColorGamePlayerBet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColorGameGetCurrentRoundRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColorGameSubscribeEventsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColorGameEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColorGameRoundStateBRC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColorGameBetConfirmation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_colorgame_colorgame_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColorGameSettlementBRC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shared_proto_colorgame_colorgame_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_colorgame_colorgame_proto_goTypes,
		DependencyIndexes: file_shared_proto_colorgame_colorgame_proto_depIdxs,
		EnumInfos:         file_shared_proto_colorgame_colorgame_proto_enumTypes,
		MessageInfos:      file_shared_proto_colorgame_colorgame_proto_msgTypes,
	}.Build()
	File_shared_proto_colorgame_colorgame_proto = out.File
	file_shared_proto_colorgame_colorgame_proto_rawDesc = nil
	file_shared_proto_colorgame_colorgame_proto_goTypes = nil
	file_shared_proto_colorgame_colorgame_proto_depIdxs = nil
}
